import React from 'react';
import {
  Hammer,
  Home,
  Zap,
  Wind,
  Ruler,
  Phone,
  MapPin,
  Clock,
  CheckCircle2,
  ArrowRight,
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  Star,
  ShieldCheck,
  HardHat,
  Smartphone,
  Mail,
  Sun,
  Moon,
  Thermometer,
  BarChart3,
  Leaf,
  Plus,
  Minus,
  Wrench,
  Droplet,
  Settings,
  Briefcase,
  TrendingUp,
  Users,
  Target,
  Lightbulb,
  MessageSquare,
  PieChart,
  Megaphone,
  Linkedin
} from 'lucide-react';

export const Icons = {
  NewBuild: Home,
  Renovation: Hammer,
  Electric: Zap,
  HVAC: Wind,
  Blueprint: Ruler,
  Phone: Phone,
  Location: MapPin,
  Clock: Clock,
  Check: CheckCircle2,
  ArrowRight: ArrowRight,
  Menu: Menu,
  Close: X,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Star: Star,
  Shield: ShieldCheck,
  HardHat: HardHat,
  Mobile: Smartphone,
  Mail: Mail,
  Sun: Sun,
  Moon: Moon,
  Thermometer: Thermometer,
  Chart: BarChart3,
  Eco: Leaf,
  Plus: Plus,
  Minus: Minus,
  Wrench: Wrench,
  Droplet: Droplet,
  Settings: Settings,
  Hammer: Hammer,
  Briefcase: Briefcase,
  TrendingUp: TrendingUp,
  Users: Users,
  Target: Target,
  Lightbulb: Lightbulb,
  MessageSquare: MessageSquare,
  PieChart: PieChart,
  Megaphone: Megaphone,
  Linkedin: Linkedin
};
